# Generated by Django 5.1.7 on 2025-03-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='attempted_questions',
            field=models.IntegerField(default=0, help_text='Number of questions attempted'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='badges_earned',
            field=models.IntegerField(default=0, help_text='Number of badges earned'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='earned_points',
            field=models.IntegerField(default=0, help_text='Total points earned from challenges'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='no_of_questions_solved',
            field=models.IntegerField(default=0, help_text='Number of questions successfully solved'),
        ),
    ]
