# Generated by Django 5.1.7 on 2025-03-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createathon', '0002_customuser_attempted_questions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='attempted_questions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='badges_earned',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='earned_points',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='no_of_questions_solved',
        ),
    ]
